name: chatkit_example
description: Just An Example to Test the functions of Pusher_ChatKit_Flutter Package
version: 0.0.1
author: TinyProgrammers Organaization
homepage: http://TinyProgrammers.ga

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  pusher_chatkit_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
